<?php
class AutorizanData {	public static $tablename = "autorizacion";
	public function __construct(){		$this->idcompany = "";		$this->idclient = "";		$this->idresiente = "";		$this->clave = "";		$this->cedula = "";		$this->nombre = "";		$this->tipo = "";		$this->manzana = "";		$this->villa = "";		$this->email = "";		$this->telefono1 = "";		$this->telefono2 = "";		$this->ini_fec = "";		$this->fin_fec = "";		$this->observacion = "";		$this->is_active = "";		$this->created_at = "NOW()";	}
	public function add(){		$sql = "INSERT INTO ".self::$tablename." (idcompany, idclient, idresidente, clave, tipo, cedula, nombre, email, telefono1, telefono2, ini_fec, fin_fec, observacion, manzana, villa, is_active, created_at) ";		$sql .= "VALUES (".$_SESSION['id_company'].", ".$_SESSION['id_client'].", ".$_SESSION['user_id'].", \"$this->clave\", \"$this->tipo\", \"$this->cedula\", \"$this->nombre\", \"$this->email\", \"$this->telefono1\", \"$this->telefono2\", \"$this->ini_fec\", \"$this->fin_fec\", \"$this->observacion\", \"$this->manzana\", \"$this->villa\", 1, $this->created_at)";		Executor::doit($sql);	}
	public static function delById($id){		$sql = "update ".self::$tablename." set is_active = 0 where id=$id";
		Executor::doit($sql);	}	public function anular(){		$sql = "UPDATE ".self::$tablename." SET observacion='Eliminado automaticamente el ".date("Y-m-d H:i:s")."', is_active=0 WHERE id=$this->id";		$valor = Executor::doit($sql);		return $valor;	}	
	public function del(){		$sql = "UPDATE ".self::$tablename." SET observacion='Eliminado por el residente el ".date("Y-m-d H:i:s")."', is_active=0 WHERE id=$this->id";		$valor = Executor::doit($sql);
		return $valor;	}
	public function update(){
		$sql = "UPDATE ".self::$tablename." SET  tipo_empresa=\"$this->tipo_empresa\", nombre=\"$this->nombre\", contacto=\"$this->contacto\", cargo=\"$this->cargo\", email=\"$this->email\", telefono1=\"$this->telefono1\", telefono2=\"$this->telefono2\", factura=\"$this->factura\", telefonofac1=\"$this->telefonofac1\", telefonofac2=\"$this->telefonofac2\", fechafac=\"$this->fechafac\", fechaini=\"$this->fechaini\", fechafin=\"$this->fechafin\", ini_fac=\"$this->ini_fac\", fin_fac=\"$this->fin_fac\", direccion=\"$this->direccion\", observacion=\"$this->observacion\", is_active=\"$this->is_active\" WHERE idclient=$this->id";		Executor::doit($sql);	}
	public static function getById($id){		$sql = "SELECT * FROM ".self::$tablename." WHERE idclient=$id";		$query = Executor::doit($sql);				return Model::one($query[0],new AutorizanData());	}	public static function getClient($estado){		$sql = "SELECT * FROM ".self::$tablename." WHERE idclient = ".$_SESSION["id_client"]." AND is_active = $estado";		$query = Executor::doit($sql); 		return Model::many($query[0],new AutorizanData());	}	public static function getPuesto($estado){ 		$sql = "SELECT * FROM ".self::$tablename." WHERE idclient = ".$_SESSION["id_client"]." AND is_active = $estado";		$query = Executor::doit($sql); echo $sql;		return Model::many($query[0],new AutorizanData());	}	
	public static function getAll($estado){		$sql = "SELECT * FROM ".self::$tablename." WHERE idresidente = ".$_SESSION["user_id"]." AND is_active = $estado";		$query = Executor::doit($sql);
		return Model::many($query[0],new AutorizanData());	}
	public static function getLike($q){		$sql = "select * from ".self::$tablename." where name like '%$q%'";		$query = Executor::doit($sql);		return Model::many($query[0],new AutorizanData());	}}
