<?php// 14 de Abril del 2014// Core.php// @brief obtiene las configuraciones, muestra y carga los contenidos necesarios.// actualizado [11-Aug-2016]
class Core {	public static $theme = "";	public static $root = "";	public static $user = null;	public static $debug_sql = false;
	public static function includeCSS(){		$path = "res/css/";		$handle=opendir($path);
		if($handle){			while (false !== ($entry = readdir($handle)))  {				if($entry!="." && $entry!=".."){					$fullpath = $path.$entry;					if(!is_dir($fullpath)){						echo "<link rel='stylesheet' type='text/css' href='".$fullpath."' />";					}				}			}			closedir($handle);		}	}
	public static function cargando(){		echo '<div style="display: flex; width: 100%; height: 100%; justify-content: center; align-items: center;"><img src="assets/images/ajax-loader.gif" alt="Imagen cargando"></div>';	}	public static function aviso(){		echo '<div style="display: flex; width: 100%; height: 100%; justify-content: center; align-items: center;"><img src="assets/images/cargando.gif" alt="Imagen cargando"></div>';	}	
	public static function alert($titulo, $texto, $tipo, $url=null){	    echo '<script>jQuery(function(){swal("'.$titulo.'", "'.$texto.'", "'.$tipo.'");});</script>';		if($url) echo '<script>window.location="index.php?view='.$url.'";</script>';	}
	public static function redir($url){		echo "<script>window.location='index.php?view=".$url."';</script>";	}
	public static function includeJS(){		$path = "res/js/";		$handle=opendir($path);
		if($handle){			while (false !== ($entry = readdir($handle)))  {				if($entry!="." && $entry!=".."){					$fullpath = $path.$entry;					if(!is_dir($fullpath)){						echo "<script type='text/javascript' src='".$fullpath."'></script>";					}				}			}			closedir($handle);		}	}			/*--------------------------------------------------------------*/	/* Function for Remove html characters	/*--------------------------------------------------------------*/	public static function remove_junk($str){		$str = nl2br($str);		$str = htmlspecialchars(strip_tags($str, ENT_QUOTES));		return $str;	}		/*--------------------------------------------------------------*/	/* Function for Uppercase first character	/*--------------------------------------------------------------*/	public static function first_character($str){		$val = str_replace('-'," ",$str);		$val = ucfirst($val);		return $val;	}		/*--------------------------------------------------------------*/	/* Function for Checking input fields not empty	/*--------------------------------------------------------------*/	function validate_fields($var){		global $errors;		foreach ($var as $str) {						$val = nl2br($str);			$val = htmlspecialchars(strip_tags($str, ENT_QUOTES));						if(isset($val) && $val==''){				$errors = $field ." No puede estar en blanco.";				return $errors;			}		}	}	/*--------------------------------------------------------------*/	/* Function for Display Session Message	   Ex echo displayt_msg($message);	/*--------------------------------------------------------------*/	public static function display_msg($valor, $msg = ''){		$output = array();		if(!empty($msg)) {			$output  = "<div class=\"alert alert-{$valor}\">";			$output .= "<button type=\"button\" class=\"close\" data-dismiss=\"alert\" aria-hidden=\"true\">×</button>";			$output .= $msg;			$output .= "</div>";						return $output;		}else{			return "" ;		}	}}
